### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated. 

### ISSUE THREAD

**Issue by namwkim** [MilllerTime/react-pointable#1]
Thanks for the wonderful and elegant package.

For your information, the following is a warning I received. I think it is not critical at this point, but it would be nice to be resolved in the future.

"module.js:362 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead."

**Comment by MilllerTime** [comment]
Happy it works for you!

Thanks for bringing this up. I just upgraded a project to React 15.5 and started noticing this myself. You're right that it's not critical, however if you're like me then you don't want to see any warnings 🙂

Expect an update shortly!

**Comment by MilllerTime** [comment]
I just pushed out a new release that should resolve this.

Just a heads up, it's a major version bump since it now requires React ^15.5.0 as a peer dependency.
