### ISSUE TITLE
TypeScript Typings

### ISSUE THREAD

**Issue by iStefo** [MilllerTime/react-pointable#3]
First, thanks for your react component.

When implementing a react application written in TypeScript, I notice that there is no typing information present for this component which forced me to either a) disable the "implicit any" warning (that globally disables type-checking for unknown modules) or b) write my own minimum viable typing information inside my project.

Since I wanted to keep the implicit any warning, I went for the later. As this is currently only useful for myself, I wanted to ask you which way you would prefer to publish typings for this component.
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html mentions two different options:

a) Bundle type information with this package (would be the simpler choice, I could create a PR with one additional file that contains the type information needed)
b) Publish an additional package to NPM that developers can install if they are using TypeScript (would be ok if you do not want to have any files in this repo that you can't update (given you are not using TypeScript...))

Please let me know what you think.

**Comment by MilllerTime** [comment]
Thanks for thinking about TS support with this component, and for working on a PR! I am fully in favor of static typing, however I haven't used TS myself outside of a little experimentation. As you are now aware, the API surface area on this component is pretty tiny and I believe the included prop-types do a great job of covering that surface _dynamically_.

Still, I understand the desire for TS support if you're already working on a TS project. As long as the definitions don't get in anyone else's way (for vanilla users or even Flow users down the road), I'm fine with including a `.d.ts` file in this repo.

It looks like option A fits the bill 👍

**Comment by iStefo** [comment]
Closing in favor of PR #4.
